### ISSUE TITLE
Pkg.add() on Windows fails.

### ISSUE THREAD

**Issue by ryanhausen** [JuliaAstro/FITSIO.jl#52] opened 2016-05-12 04:36 UTC
When I tried to add the package on a windows machine the install fails. It doesn't copy cfitsio.dll to the /lib directory. I put it there and did a Pkg.build() and everything worked.

Here's the output from the console:

julia> Pkg.add("FITSIO")
INFO: Cloning cache of FITSIO from git://github.com/JuliaAstro/FITSIO.jl.git
INFO: Installing FITSIO v0.8.3
INFO: Building FITSIO

PowerShell[.exe] [-PSConsoleFile <file> | -Version <version>]
    [-NoLogo] [-NoExit] [-Sta] [-Mta] [-NoProfile] [-NonInteractive]
    [-InputFormat {Text | XML}] [-OutputFormat {Text | XML}]
    [-WindowStyle <style>] [-EncodedCommand <Base64EncodedCommand>]
    [-File <filePath> <args>] [-ExecutionPolicy <ExecutionPolicy>]
    [-Command { - | <script-block> [-args <arg-array>]
                  | <string> [<CommandParameters>] } ]

PowerShell[.exe] -Help | -? | /?

-PSConsoleFile
    Loads the specified Windows PowerShell console file. To create a console
    file, use Export-Console in Windows PowerShell.

-Version
    Starts the specified version of Windows PowerShell.
    Enter a version number with the parameter, such as "-version 2.0".

-NoLogo
    Hides the copyright banner at startup.

-NoExit
    Does not exit after running startup commands.

-Sta
    Starts the shell using a single-threaded apartment.
    Single-threaded apartment (STA) is the default.

-Mta
    Start the shell using a multithreaded apartment.

-NoProfile
    Does not load the Windows PowerShell profile.

-NonInteractive
    Does not present an interactive prompt to the user.

-InputFormat
    Describes the format of data sent to Windows PowerShell. Valid values are
    "Text" (text strings) or "XML" (serialized CLIXML format).

-OutputFormat
    Determines how output from Windows PowerShell is formatted. Valid values
    are "Text" (text strings) or "XML" (serialized CLIXML format).

-WindowStyle
    Sets the window style to Normal, Minimized, Maximized or Hidden.

-EncodedCommand
    Accepts a base-64-encoded string version of a command. Use this parameter
    to submit commands to Windows PowerShell that require complex quotation
    marks or curly braces.

-File
    Runs the specified script in the local scope ("dot-sourced"), so that the
    functions and variables that the script creates are available in the
    current session. Enter the script file path and any parameters.
    File must be the last parameter in the command, because all characters
    typed after the File parameter name are interpreted
    as the script file path followed by the script parameters.

-ExecutionPolicy
    Sets the default execution policy for the current session and saves it
    in the $env:PSExecutionPolicyPreference environment variable.
    This parameter does not change the Windows PowerShell execution policy
    that is set in the registry.

-Command
    Executes the specified commands (and any parameters) as though they were
    typed at the Windows PowerShell command prompt, and then exits, unless
    NoExit is specified. The value of Command can be "-", a string. or a
    script block.

    If the value of Command is "-", the command text is read from standard
    input.

    If the value of Command is a script block, the script block must be enclosed
    in braces ({}). You can specify a script block only when running PowerShell.exe
    in Windows PowerShell. The results of the script block are returned to the
    parent shell as deserialized XML objects, not live objects.

    If the value of Command is a string, Command must be the last parameter
    in the command , because any characters typed after the command are
    interpreted as the command arguments.

    To write a string that runs a Windows PowerShell command, use the format:
        "& {<command>}"
    where the quotation marks indicate a string and the invoke operator (&)
    causes the command to be executed.

-Help, -?, /?
    Shows this message. If you are typing a PowerShell.exe command in Windows
    PowerShell, prepend the command parameters with a hyphen (-), not a forward
    slash (/). You can use either a hyphen or forward slash in Cmd.exe.

EXAMPLES
    PowerShell -PSConsoleFile SqlSnapIn.Psc1
    PowerShell -version 2.0 -NoLogo -InputFormat text -OutputFormat XML
    PowerShell -Command {Get-EventLog -LogName security}
    PowerShell -Command "& {Get-EventLog -LogName security}"

    # To use the -EncodedCommand parameter:
    $command = 'dir "c:\program files" '
    $bytes = [System.Text.Encoding]::Unicode.GetBytes($command)
    $encodedCommand = [Convert]::ToBase64String($bytes)
    powershell.exe -encodedCommand $encodedCommand
INFO: Attempting to Create directory C:\Users\User\.julia\v0.4\FITSIO\deps\downloads
INFO: Downloading file ftp://heasarc.gsfc.nasa.gov/software/fitsio/c/cfitsio_MSVC_64bit_DLL_3370.zip
INFO: Done downloading file ftp://heasarc.gsfc.nasa.gov/software/fitsio/c/cfitsio_MSVC_64bit_DLL_3370.zip
INFO: Attempting to Create directory C:\Users\User\.julia\v0.4\FITSIO\deps\src
INFO: Attempting to Create directory C:\Users\User\.julia\v0.4\FITSIO\deps
INFO: Directory C:\Users\User\.julia\v0.4\FITSIO\deps already created

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: C:\Users\User\.julia\v0.4\FITSIO\deps\downloads\cfitsio_MSVC_64bit_DLL_3370.zip

Extracting  cfitsio.dll
Extracting  cfitsio.lib
Extracting  FPack.exe
Extracting  Funpack.exe
Extracting  TestProg.exe
Extracting  fpackguide.pdf
Extracting  fitsio.h
Extracting  License.txt
Extracting  longnam.h
Extracting  README.win
Extracting  testprog.std
Extracting  testprog.tpt
Extracting  testprog.out
Extracting  testprog.c

Everything is Ok

Files: 14
Size:       2161783
Compressed: 1078860
INFO: Attempting to Create directory C:\Users\User\.julia\v0.4\FITSIO\deps\usr\lib
INFO: Changing Directory to C:\Users\User\.julia\v0.4\FITSIO\deps\src
===============================[ ERROR: FITSIO ]================================

LoadError: could not spawn `cp cfitsio.dll 'C:\Users\User\.julia\v0.4\FITSIO\deps\usr\lib\cfitsio.dll'`: no such file or directory (ENOENT)
while loading C:\Users\User\.julia\v0.4\FITSIO\deps\build.jl, in expression starting on line 55

================================================================================

====================================================[ BUILD ERRORS ]====================================================

WARNING: FITSIO had build errors.

 - packages with build errors remain installed in C:\Users\User\.julia\v0.4
 - build the package(s) and all dependencies with `Pkg.build("FITSIO")`
 - build a single package by running its `deps/build.jl` script

========================================================================================================================
INFO: Package database updated
INFO: METADATA is out-of-date — you may not have the latest version of FITSIO
INFO: Use `Pkg.update()` to get the latest versions of your packages

**Comment by kbarbary** [comment] 2016-05-12 04:44
It looks like the build process tries to copy `cfitsio.dll` from `C:\Users\User.julia\v0.4\FITSIO\deps\src`, but fails. Is that not the right directory?

It's odd because the appveyor build succeeds...

**Comment by kbarbary** [comment] 2016-08-02 00:44
Without a Windows machine and with AppVeyor tests succeeding, it's hard to further diagnose this. I'm closing it for now but feel free to reopen if the problem persists or if someone else can reproduce.

**Closed** 2016-08-02 00:44 UTC

**Comment by tkelman** [comment] 2016-08-02 22:39
This is because you're shelling out to `cp`, which happens to be on the path on AppVeyor but usually isn't on Windows. This is why I despise permanently adding things to PATH.

Try this: https://github.com/JuliaOpt/NLopt.jl/blob/a3692f57cf64e5a0cab5ea7d75ba037feebc6ee7/deps/build.jl#L41
Messy but should work.

**Comment by kbarbary** [comment] 2016-08-02 23:23
Thanks for the hint Tony. I think I did the right thing in #54.
